Another fix

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -12,29 +12,30 @@ jobs:
     strategy:
         matrix:
           go-version: [ '1.22.x', 'stable' ]
-    build:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout code
-          uses: actions/checkout@v4
 
-        - name: Set up Go
-          uses: actions/setup-go@v5
-          with:
-            go-version: ${{ matrix.go-version }} 
-            cache: true
+    runs-on: ubuntu-latest
+    
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-        - name: Check code formatting
-          run: |
-            # Fails if gofumpt finds any files that need formatting.
-            if [ -n "$(gofumpt -l .)" ]; then
-              echo "Go code is not formatted:"
-              gofumpt -l .
-              exit 1
-            fi
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: ${{ matrix.go-version }} 
+          cache: true
 
-        - name: Build
-          run: go build -v ./...
+      - name: Check code formatting
+        run: |
+          # Fails if gofumpt finds any files that need formatting.
+          if [ -n "$(gofumpt -l .)" ]; then
+            echo "Go code is not formatted:"
+            gofumpt -l .
+            exit 1
+          fi
 
-        - name: Test
-          run: go test -v -race ./...
+      - name: Build
+        run: go build -v ./...
+
+      - name: Test
+        run: go test -v -race ./...
